src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="array")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="author", orphanRemoval=true)
     * @ORM\OrderBy({"date" = "DESC"})
     */
    private $events;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $pseudo;

    /**
     * @ORM\ManyToMany(targetEntity=Event::class, inversedBy="participants")
     */
    private $participations;

    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->participations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setAuthor($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getAuthor() === $this) {
                $event->setAuthor(null);
            }
        }

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getParticipations(): Collection
    {
        return $this->participations;
    }

    public function addParticipation(Event $participation): self
    {
        if (!$this->participations->contains($participation)) {
            $this->participations[] = $participation;
        }

        return $this;
    }

    public function removeParticipation(Event $participation): self
    {
        if ($this->participations->contains($participation)) {
            $this->participations->removeElement($participation);
        }

        return $this;
    }
}

templates/participe/index.html.twig
{% extends '_template.html.twig' %}

{% block title %}
    {{ event.name }}
{% endblock %}

{% block content %}
    <div class="section has-background-info-dark">
        <div class="columns has-background-warning">
            <div class="column">
                <figure class="image is-1by1">
                    <img src="https://loremflickr.com/1024/1024/conference,office/all?lock={{ event.id }}">
                </figure>
            </div>

            <div class="column is-half">
                <div class="content">
                    <h3 class="subtitle">Evenement : {{ event.name }}</h3>
                    <p><b>Description :</b> <i>{{ event.description }}</i></p>
                </div>

                {% include 'includes/flash.html.twig' %}
                    {% if app.user %}
                        <div class="section pt-0">
                            {% if is_granted('EVENT_PARTICIPATE', event) %}
                                <p>Vous participez à cet événement.</p>
                                <a href="{{ path('event_cancel_participation', {id: event.id, token: csrf_token('event-cancel-participation')}) }}" class="button is-danger is-light is-fullwidth">
                                    Je ne participe plus.
                                </a>
                            {% else %}
                                <a href="{{ path('event_participate', {id: event.id, token: csrf_token('event-participate')}) }}" class="button is-success is-light is-fullwidth">
                                    Je participe !
                                </a>
                            {% endif %}
                        </div>
                    {% else %}
                        <h4 class="subtitle has-text-centered">Connectez-vous pour participer !</h4>
                        <div class="columns">
                            <div class="column">
                                <a href="{{ path('app_register') }}" class="button is-info is-light is-fullwidth">
                                    Inscription
                                </a>
                            </div>
                            <div class="column">
                                <a href="{{ path('app_login') }}" class="button is-success is-light is-fullwidth">
                                    Je me connecte !
                                </a>
                            </div>
                        </div>
                    {% endif %}

                <div class="box">
                    <div class="columns is-vcentered">
                        <div class="column">
                            <strong>Organisé par :</strong>
                            <span class="has-text-primary">{{ event.author.pseudo }}</span>
                        </div>
                        <div class="column is-one-fifth">
                            <figure class="image is-48x48 mb-0">
                                <img src="https://robohash.org/{{ event.author.pseudo }}?set=set5">
                            </figure>
                        </div>
                    </div>
                    <div class="content">
                        <p class="is-size-7 has-text-centered">
                            Le <strong>{{ event.date|date('d/m/Y') }}</strong>
                        </p>
                        <hr>

                        <h5 class="title">Inviter quelqu'un :</h5>
                        
                        {# {% if invite_form is defined %} #}
                            {{ form_start(invite_form) }}

                            {{ form_row(invite_form.email, {
                                label: 'Adresse email:'
                            }) }}

                            <button type="submit" class="button is-info is-fullwidth">Inviter un ami !</button>

                            {{ form_end(invite_form) }}
                        {# {% endif %} #}

                        <hr>
                        <h5 class="title">Participants : {{ event.participants|length }}</h5>
                        <div class="columns is-multiline">
                            {% for participant in event.participants %}
                                <div class="column is-one-fifth">
                                    <figure class="image is-48x48 mb-0">
                                        <img src="https://robohash.org/{{ participant.username }}?set=set5">
                                    </figure>
                                    <p class="is-size-7 has-text-centered">{{ participant.username }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/participe/participate_list.html.twig
{% extends '_template.html.twig' %}

{% block title %}
    {# Mes participations: {{ organized_events|length }} #}
{% endblock %}

{% block content %}
    {# {% include 'includes/event_list.html.twig' with {event_list: organized_events} %} #}

    {% include 'includes/pagination.html.twig' with {
        current: pagination_current,
        total: organized_events|length,
        offset: pagination_offset
    } %}
{% endblock %}